### ISSUE TITLE
page DE et FR ne s'affiche pas sur le site 

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#113]
http://31.211.16.159:8203/fr/docs/HowToInstallGame/
http://31.211.16.159:8203/de/docs/HowToInstallGame/
should be work :/

**Comment by GemInee** [comment]
Looks like it works now:
![image](https://user-images.githubusercontent.com/33014703/213860847-910dd1f5-736a-45b2-8462-f613c8750843.png)
![image](https://user-images.githubusercontent.com/33014703/213860852-8355c539-9992-43fc-a608-1f33a509f78d.png)

**Comment by Fr-Dae** [comment]
this page are english

**Comment by GemInee** [comment]
I tested it and now it works fine:
![image](https://user-images.githubusercontent.com/33014703/215992746-5491d9d0-9dd9-43a7-90f6-893e86717c33.png)
![image](https://user-images.githubusercontent.com/33014703/215992791-560b86ee-c8bc-4766-b2eb-4bd30e3bcb68.png)
![image](https://user-images.githubusercontent.com/33014703/215992882-01a79df1-5c8a-4f73-b37d-b8dd6b42233c.png)
![image](https://user-images.githubusercontent.com/33014703/215992929-371a2aef-5c4f-4007-8d18-58d1722a3338.png)

**Comment by Fr-Dae** [comment]
nice
