### ISSUE TITLE
add  mermaid and markdown extra ?

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#121]
https://michelf.ca/projects/php-markdown/extra/#table
https://python-markdown.github.io/extensions/extra/
https://mermaid.js.org/intro/

**Comment by GemInee** [comment]
The plugin could not be installed.
There was a version error, although directly on the Docusaurus documentation site, there is a simple instruction on how to connect this plugin.

So far no idea how to fix this quickly.
Later I'll study the question some more, maybe this is already solved by the developers themselves...

Or there is another solution.

**Comment by Fr-Dae** [comment]
this 2 page are english

**Comment by GemInee** [comment]
Mermaid added.

**Comment by Fr-Dae** [comment]
close issue so ?

**Comment by GemInee** [comment]
Если отложить подключение других плагинов на более позднее время, то да... я могу подготовить PR и закроем issue

**Comment by Fr-Dae** [comment]
> 

i will wait , i don't understand if i should close this issues
