### ISSUE TITLE
Implement changelog-api

### ISSUE THREAD

**Issue by GemInee** [Unitystation-fork/Unitystation-WikiV2#134]
Instruictuins from GPT Chat to do this:
# Changelog API

A Django project for managing build versions and changes.

## Languages used

    Python
    Django
    SQL
    Docker

## Description

This project is an API that allows you to manage build versions and changes for your software. It includes a database model for storing build versions and changes, as well as a REST API for retrieving and updating this data. The API also includes a simple web interface for viewing the data.
Credits

    Author: John Doe
    Organization: Example Inc.

## Project Goals

The goal of this project is to provide an easy way for software developers to keep track of changes in their builds. The target audience is software developers and project managers.

## Installation

To install this project, you will need to have Docker and Docker Compose installed on your machine. Then, clone the repository and run the following command:

`docker-compose up`

This will build the necessary images and start the services. You can then access the API at http://localhost:8000.

### Deployment

To deploy this application, you will need to have Docker and Docker Compose installed on your machine.

    Clone the repository:

git clone https://github.com/yourusername/changelog-api.git

    Build the Docker image:

docker-compose -f dev-compose.yml build

    Start the application:

docker-compose -f dev-compose.yml up

Your application should now be running on port 8000. You can access it in your web browser by navigating to http://localhost:8000.

To run this in production, you may want to use a reverse proxy like Nginx or Apache.

You can also use docker-compose -f prod-compose.yml up for production instead of docker-compose -f dev-compose.yml up

Please make sure to keep the .env file and keep the secret key used in production secret.
Deploying with other options

If you wish to deploy with other options such as using ssh, you can use USE_SSH=true yarn deploy or GIT_USER=<Your GitHub username> yarn deploy

You can also use yarn build to generate a static content into the build directory and can be served using any static contents hosting service.

Please make sure to keep the .env file and keep the secret key used in production secret.

## Updating

To update the project to the latest version, simply pull the latest changes from the repository and run the following command:

`docker-compose up --build`

This will rebuild the images and restart the services with the latest code.

## Usage

You can interact with the API using any HTTP client, such as curl or Postman. The API includes endpoints for creating, retrieving, updating, and deleting build versions and changes. 
You can also access the web interface by navigating to http://localhost:8000 in your web browser.
Contribution and Development

If you would like to contribute to this project, please feel free to submit pull requests.

### API Usage Examples
Get all changes of a specific category

curl http://localhost:8000/changes?category=NEW

This will return a JSON object containing an array of all the changes in the database that belong to the specified category, with each change having the following properties: build_version, category, description, author.

Example response:

[
    {
        "build_version": "1.0",
        "category": "NEW",
        "description": "Added new feature X",
        "author": "John Doe"
    },
    {
        "build_version": "1.1",
        "category": "NEW",
        "description": "Added new feature Y",
        "author": "Jane Smith"
    }
]

## Note

Please make sure to keep the .env file and keep the secret key used in production secret.

## License

This project is open-source and licensed under the MIT License.

## Support

If you need help or have any questions, please feel free to reach out to the author or open an issue on the repository.

**Comment by GemInee** [comment]
Process stop at step: "Clone the repository"
![image](https://user-images.githubusercontent.com/33014703/214772670-76233237-81fc-4afa-82e9-4ecd56c8600b.png)

Need help.

**Comment by Fr-Dae** [comment]
pour ce sujet, je vous recommande fortement de contacter gilles sur le discord de unitystation dans l'onglet #dev-general pour lui dire que vous vous interessé au fonctionnement de son programme changelog-api et que vous aimeriez plus d'information a ce sujet, 

moi je me suis contenté de copier coller la documentation et certains scripte dans chatGPT et de lui demandé de m'ecrir un readme.md 
s'il dit de la merde c'est qu'il manque de contexte et je ne peux pas vous donner plus de contexte.

gilles peux sans doute

**Comment by GemInee** [comment]
I need devops skills, which I don't have, to configure the docker file.
I do not know how to configure it so that the container services can be connected to at least from the host.

Also note that this is a completely self-contained application.
I think it should be configured and deployed by a specialist.

There is no documentation on how to deploy and configure it.

I will leave it open and remove the branch because the application requires its own repository and there is no need to link it directly to a wiki project.

If this app is as good as they say, I don't need to hear about it :)

**Comment by GemInee** [comment]
I propose to close this issue on the Wiki, and form a repository separately for this application and already work with it as an independent project.
