### ISSUE TITLE
job menu order

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#142]
1. Command
2. Security
3. Engineering
4. Science
5. Medical
6. Cargo
7. Service
8. Synthetic
9. Ghost
10. Antagonist
11. Protagonist

**Comment by GemInee** [comment]
No order for:
Centcom roles
Entertainment roes
Special

And we dont have category for Protagonist roles

![image](https://user-images.githubusercontent.com/33014703/215922548-3e144e24-2527-4c64-9d30-a9e4383cf9b5.png)

**Comment by Fr-Dae** [comment]
Antagonist
Protagonist = centcom, spetial

**Comment by GemInee** [comment]
Did I understand correctly to group the Centcom, Entertainment, and Special categories into the Protagonist category?

**Comment by GemInee** [comment]
Like this:
![image](https://user-images.githubusercontent.com/33014703/215962004-176384de-88c5-4af3-bc12-60acb0d577c2.png)

**Comment by Fr-Dae** [comment]
Entertainment it's like clown and mime, so it's more civilian roles

**Comment by GemInee** [comment]
Made a correction.
Maybe not everything is as it should be.
But by analogy, it shouldn't be a problem to fix the menu as it should be.
