### ISSUE TITLE
ctrl selection don't work

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#143]
generaly when you have a div / grill, you can use Ctrl Clic to selection a colonne and not a lign
not work atm

**Comment by GemInee** [comment]
I'm not quite sure what you mean.
Can you give me a link to the site with the behavior you're interested in?

**Comment by Fr-Dae** [comment]
https://youtu.be/qRU3RSxf8Dk
https://youtu.be/NCNWyQ0xTHw

**Comment by GemInee** [comment]
This behavior is not site-side programming code.

Your video is made in the Firefox browser, apparently.
I got exactly what is in the video just by installing the browser.

You need to use a special extension for Google chrome.
The other browsers are similar, this behavior is built in or requires an extension.

Issue can be closed.

**Comment by Fr-Dae** [comment]
Why does the column selection work correctly on many sites without problems, but not on ours?

**Comment by GemInee** [comment]
Getting the problem right is half the solution.
:)

I could have solved it in 5 minutes the day the problem occurred if it had been immediately clear that it was a browser bug and not site behavior.
And it's not "not working", it's working but "not right".

Immediately it becomes clear what to check and where to look for the error.
:)
