### ISSUE TITLE
Edit this page button not working

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#144]

**Comment by Fr-Dae** [comment]
ok desable it

**Comment by GemInee** [comment]
Хорошо.
Если ссылку исправить, то она будет выглядеть например так:
https://github.com/Unitystation-fork/Unitystation-WikiV2/blob/main/docs/index.md

Можно посмотреть как будет выглядеть результата перехода по ней для того, у кого есть доступ к репозиторию и у кого нет.
