### ISSUE TITLE
Pieds de page fonctionnnel

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#18]
нижний колонтитул должен позволять переходить с одной страницы на другую
или из одной категории в другую

**Comment by Mathis-Lague** [comment]
J'adore les pieds

**Comment by Fr-Dae** [comment]
> J'adore les pieds

Quoi, mais t'es qui toi ? xD

**Comment by GemInee** [comment]
We need an explanation of the problem.

Are we talking about the footer?
If so, I need a list of references for it, so I can mark it up there.

Or are we talking about the end of the page, where there are navigation buttons to go to the next or previous document?
If so, it already work:


![Image](https://user-images.githubusercontent.com/33014703/213373755-58be2f9d-09c9-4d87-8e37-73122fdba685.png)

**Comment by GemInee** [comment]
And aslo we have breadcrumbs in top of the page:


![Image](https://user-images.githubusercontent.com/33014703/213374002-3f8b85d9-6f58-45ff-9cc1-73d3791baf8b.png)

**Comment by Fr-Dae** [comment]
je parle de l'utilisation du document suivant comme pieds de page
/home/dae/GIT/Unitystation-WikiV2/docs/html/rolesnavbar.md

un exemple ici

https://tgstation13.org/wiki/Jobs

**Comment by GemInee** [comment]
This is how rolesnavbar looks now:

![Image](https://user-images.githubusercontent.com/33014703/213380314-955a3376-c364-477c-8261-572a1b9b2301.png)

This is correct view or we need to refactor this block.

**Comment by Fr-Dae** [comment]
nice, 
es-ce possible de reduire un peu l'espacement entre le texte et les lignes ?
que le bloc soit plus, "compresser"

**Comment by GemInee** [comment]
To make exactly these changes, we need to convert this block of MD markup into a JS component, which we will embed in our documents.

Now the table is rendered by default, and if we change its appearance, we will affect all tables.

Then I suggest that in release 2.2 we embed the table in this form.
And in future releases already change.

Additionally you can try to put rolesnavbar in a collapsable block, so that the user unwraps it himself, when he needs it.

**Comment by GemInee** [comment]
I can try to modify all table to this style:


![Image](https://user-images.githubusercontent.com/33014703/213398082-2601a383-5522-4d58-ba59-74774dd6602b.png)

This how looks other tables in same style:


![Image](https://user-images.githubusercontent.com/33014703/213398622-75bf5837-c935-4e62-8b3c-7ab4078a8e83.png)

**Comment by Fr-Dae** [comment]
APPROVED
