### ISSUE TITLE
supprimer espace vide et inutile dans le CSS

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#19]
![Image](https://user-images.githubusercontent.com/23202421/210760909-995c517d-8822-4c54-809f-88edb131fbdf.png)

**Comment by GemInee** [comment]
Current layout


![Image](https://user-images.githubusercontent.com/33014703/213365233-80c92d39-ca98-413b-a965-0b1a27fb05ce.png)

**Comment by Fr-Dae** [comment]
can i close this issues now ?
