### ISSUE TITLE
Fix internal MD links

### ISSUE THREAD

**Issue by GemInee** [Unitystation-fork/Unitystation-WikiV2#203]

**Comment by Fr-Dae** [comment]
> Construction.md
> Hacking-Guide.md
moved to job/engy

> Space-Law.md
Move to job security / Sec Off

**Comment by GemInee** [comment]
New files in locales

FR:
Battle-royale.md
Standard-Operating-Procedure.md
Security-Officer-Guide.md
Robotics-Guide.md
Offical_Station_Maps.md
Guide-to-Atmospherics.md
Chemistry.md

DE:
Access.md
Battle-royale.md
Combat_Guide.md
Standard-Operating-Procedure.md
Space-Law.md
Antagonist_roles.md
Robotics-Guide.md
Nuclear-Operative.md
Shitsec.md
RP-words-and-abbreviations.md
Cook.md
Janitor.md
Warden.md
Central-Command-Officer.md
Clown.md
Captain.md
Head-of-Personnel.md
Cargo-Technician.md
Cargonia.md
Traitor.md
Xenomorph.md
