### ISSUE TITLE
could we delet all mention about "blog" ?

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#210]
@GemInee

**Comment by GemInee** [comment]
What mentions of the blog bother you?

**Comment by Fr-Dae** [comment]
/GIT/Unitystation-WikiV2/i18n/FR/docusaurus-plugin-content-blog/
for exemple

**Comment by GemInee** [comment]
It would be easier for me to do well all at once if there were examples of all the options.

With the blog folder in localizations I got it.
Are there any other places where "blog" should be removed?

**Comment by GemInee** [comment]
I deleted everything I could find.
