### ISSUE TITLE
traduction section médicale

### ISSUE THREAD

**Issue by Nacent** [Unitystation-fork/Unitystation-WikiV2#22]

**Comment by Fr-Dae** [comment]
https://github.com/Unitystation-fork/Unitystation-WikiV2/commit/b81c034f59eb2e2504864b7a22639dfcb87d0231
https://github.com/Unitystation-fork/Unitystation-WikiV2/commit/a0065f6b45d78bac7c8bb4e04c7a39d5dcfafd08
