### ISSUE TITLE
traduction du répertoire job/ghost

### ISSUE THREAD

**Issue by LePapeDeWesteros** [Unitystation-fork/Unitystation-WikiV2#31]
traduction

**Comment by Fr-Dae** [comment]
attention, le dossier de travail est maintenant /i18n/FR

**Comment by Fr-Dae** [comment]
https://github.com/Unitystation-fork/Unitystation-WikiV2/commit/ddf865756f3acedd301ab69062f07e169a37929c

**Comment by Fr-Dae** [comment]
https://github.com/Unitystation-fork/Unitystation-WikiV2/pull/176
