### ISSUE TITLE
Logo et favicon

### ISSUE THREAD

**Issue by GemInee** [Unitystation-fork/Unitystation-WikiV2#54]

**Comment by Fr-Dae** [comment]
![UnityLogo](https://user-images.githubusercontent.com/23202421/211212389-c3ac7c7a-dd0c-4386-bc77-142dcb43c407.png)
![Unitytitle](https://user-images.githubusercontent.com/23202421/211212392-190afe28-a1be-4ad1-a840-059219cc2961.png)
