### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by GemInee** [Unitystation-fork/Unitystation-WikiV2#69]
A small number of duplicate image files have been found in the project.

Some of the files have identical names, but different images.
Some have identical names and an identical image.
In all cases, the files are simply placed in different folders.

You need to determine what to do with duplicates with the same name but different content.

**Comment by Fr-Dae** [comment]
pourrais tu me lister les nom et image en question s'il te plait ?

**Comment by GemInee** [comment]
Duplicates (with diff):
```
\Unitystation-WikiV2\static\img\chairs_chair.png
\Unitystation-WikiV2\static\img\construction\chairs_chair.png
```

```
\Unitystation-WikiV2\static\img\chairs_wooden_chair.png
\Unitystation-WikiV2\static\img\construction\chairs_wooden_chair.png
```

```
\Unitystation-WikiV2\static\img\cloning_scanner.png
\Unitystation-WikiV2\static\img\machines\cloning_scanner.png
```

Duplicate (no diff):
```
\Unitystation-WikiV2\static\img\construction\stack_objects_sheet-glass.png
\Unitystation-WikiV2\static\img\machines\stack_objects_sheet-glass.png
```
