### ISSUE TITLE
Sub categorie color ?

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#94]
Dans le CSS du site, es-ce possible d'ajouter des couleur differente pour chaque sous categorie ? pour facilité la lisibilité

**Comment by Fr-Dae** [comment]
![2023-01-23-154013_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/214068319-cdd138bb-b177-4389-880e-ce7256d69046.png)

**Comment by GemInee** [comment]
If you think there is a problem with the readability of the category hierarchy, I suggest you consider this option:
![image](https://user-images.githubusercontent.com/33014703/214070997-0b5ce73b-d47d-4c77-afff-059134502500.png)

Remove the indentation of the items, and also increase the indentation of the subcategory.

This way the menu becomes more compact and the hierarchy as clear as possible.

And it saves us from having to add lots of colors, which might confuse the reader (and what does this color mean?) And also saves us from having to select colors so that they do not violate the overall palette of the site.

What do you think of this solution?

Plus, it can be done with built-in tools, if I've got it right.

**Comment by Fr-Dae** [comment]
ok pour plus de tabulation

es-ce possible d'avoir la fleche deroulante a gauche pour un  test ?

**Comment by GemInee** [comment]
Like this?

![image](https://user-images.githubusercontent.com/33014703/214076575-135651c8-c4cb-466f-979c-ee11621095ac.png)

**Comment by Fr-Dae** [comment]
a a gauche du mot, pas a droite. comme sous windows

![2023-01-23-162341_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/214078169-f210fb41-e77c-4f49-b2a0-8892effa6350.png)

**Comment by Fr-Dae** [comment]
@GemInee

**Comment by GemInee** [comment]
@Fr-Dae 
A cursory analysis of the task shows that it cannot be done by the regular settings.
So far, I haven't been able to find the appropriate style settings through the development tools.

So far, the task does not look simple and clearly requires intervention in the theme layout.

How much time it will take to find the right settings for the theme is not clear.
So far I have not managed in any way to get the desired result...

**Comment by GemInee** [comment]
@Fr-Dae 
Я правильно понимаю, что утвержден вариант с удалением отступов (более плотное меню) и увеличением табуляции, для более явной иерархии?

@Nacent 
Почему вы сняли с себя задачу?
Вы вполне могли бы внести эти правки, тем более они все могут быть сделаны настройками темы.

**Comment by Fr-Dae** [comment]
@GemInee Oui, avoir des tabulation plus grande améliorera la lisibilité
de-même pour reduire l'espace entre les ligne (verticalement)

pour les flèche, si ce n'est pas possible (ou trop complexe ) de les avoir a gauche et non a droite, ,c'est triste mais je m'y ferais.
c'est juste plus intuitif a gauche comme windows,  ou linux.


s'il est possible de réduire la largeur de la fenetre "menu burger" de moitié c'est bien.

**Comment by GemInee** [comment]
![image](https://user-images.githubusercontent.com/33014703/214800776-63877a5f-2d60-47fd-91b0-a99ca048cfed.png)
Like this?

**Comment by Fr-Dae** [comment]
![2023-01-26-102510_1920x1080_scrot](https://user-images.githubusercontent.com/23202421/214801242-6d36bbf8-2011-4180-8d5c-f043dba4e0dc.png)

menu burger

**Comment by GemInee** [comment]
![image](https://user-images.githubusercontent.com/33014703/214801996-89eec5ff-ea87-45b1-8928-6e3205817ee8.png)

Or like this if you look it mobile version

**Comment by Fr-Dae** [comment]
Or like this if you look it mobile version
mobile version, @Nacent say me it's called "menu burger" when you have a menu panel
