### ISSUE TITLE
edit button, bellow page, don't work, shoudl link with github "how to contribute" ?

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#96]

**Comment by GemInee** [comment]
We currently do not have an edit link at the end of the pages.
Is this issue still relevant in this case?

Alternatively, we could add a link in the footer to our github for files like how to contribute, where the user can read the rules and how to make changes.

You can make a separate task for this, and prepare a file to which the link from footer will point.

**Comment by Fr-Dae** [comment]
footer link is good for me

**Comment by GemInee** [comment]
What file should I link to?

**Comment by Fr-Dae** [comment]
le bouton edit => une page qui explique comment contribuer au projet github/wiki

**Comment by GemInee** [comment]
This?
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
or we have own "Contribute.md"?

I often switch contexts, so in such tasks it would be nice to have an explicit link where to redirect the user. =)

Right now I have no ideas other than to link to the manual from github itself, link to the project page on github, or find some Contribute file in the project and link to it.

Usually such files are in the root, right next to Readme.md.
But i don't see anything like this...

**Comment by Fr-Dae** [comment]
exacte
