### ISSUE TITLE
Maybe reme chapter 2 "User Interface" by "what i see" ? or juste " HUD" ?

### ISSUE THREAD

**Issue by Fr-Dae** [Unitystation-fork/Unitystation-WikiV2#97]

**Comment by GemInee** [comment]
Я думаю, чтобы не вводить игрока в заблуждение нужно использовать, или термин User Interface или HUD.
Предлагаю пока оставить User interface, как более универсальный и всеобъемлющий термин.

**Comment by Fr-Dae** [comment]
OK, je vais faire la modification sur les pages, merci
